In [9]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import OneHotEncoder
import pandas as pd
import tensorflow as tf
from sqlalchemy import create_engine
import psycopg2 as psy
from urllib.parse import quote

In [10]:
engine = create_engine('postgresql+psycopg2://user:%s@localhost:5432/National_Parks' % quote('password'))

In [11]:
conn = engine.connect()

park_df = pd.read_sql('SELECT * FROM nationalparks;', conn)

conn.close()

park_df.head()

,park_code,park_name,states,acres,latitude,longitude,ranks,visitors,percentage
0,ACAD,Acadia,ME,47390.0,44.35,-68.21,7,3437286,0.0378
1,ARCH,Arches,UT,76519.0,38.68,-109.57,17,1659702,0.0182
2,BADL,Badlands,SD,242756.0,43.75,-102.50,28,970998,0.0107
3,BIBE,Big Bend,TX,801163.0,29.25,-103.25,44,463832,0.0051
4,BISC,Biscayne,FL,172924.0,25.65,-80.08,30,708522,0.0078

In [2]:
# Generate our categorical variable list
park_cat = park_df.dtypes[park_df.dtypes == "object"].index.tolist()

# Check the number of unique values in each column
park_df[park_cat].nunique()

Genus                  6184
Category                 14
Park Name                56
Conservation Status       5
Nativeness                2
dtype: int64

In [3]:
# Check the unique value counts to see if binning is required
park_df.Nativeness.value_counts()

Native        73425
Not Native    10054
Name: Nativeness, dtype: int64

In [4]:
# Create a OneHotEncoder instance
enc = OneHotEncoder(sparse=False)

# Fit and transform the OneHotEncoder using the categorical variable list
encode_df = pd.DataFrame(enc.fit_transform(park_df[park_cat]))

# Add the encoded variable names to the DataFrame
encode_df.columns = enc.get_feature_names(park_cat)
encode_df.head()

,Genus_Abaeis,Genus_Abelia,Genus_Abgrallaspis,Genus_Abies,Genus_Abietinella,Genus_Abildgaardia,Genus_Ablabesmyia,Genus_Ablennes,Genus_Abronia,Genus_Abrus,...,Park Name_Yellowstone,Park Name_Yosemite,Park Name_Zion,Conservation Status_Endangered,Conservation Status_In Recovery,Conservation Status_Least Concern,Conservation Status_Species of Concern,Conservation Status_Threatened,Nativeness_Native,Nativeness_Not Native
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0

In [5]:
# Merge one-hot encoded features and drop the originals
park_df = park_df.merge(encode_df,left_index=True, right_index=True)
park_df = park_df.drop(park_cat,1)
park_df.head()

,Genus_Abaeis,Genus_Abelia,Genus_Abgrallaspis,Genus_Abies,Genus_Abietinella,Genus_Abildgaardia,Genus_Ablabesmyia,Genus_Ablennes,Genus_Abronia,Genus_Abrus,...,Park Name_Yellowstone,Park Name_Yosemite,Park Name_Zion,Conservation Status_Endangered,Conservation Status_In Recovery,Conservation Status_Least Concern,Conservation Status_Species of Concern,Conservation Status_Threatened,Nativeness_Native,Nativeness_Not Native
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0

In [6]:
# Remove Nativeness target from features data
y = park_df.Nativeness_Native
X = park_df.drop(columns=["Nativeness_Native","Nativeness_Not Native"])


# Split training/test datasets
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, stratify=y)

# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [7]:
# Create a random forest classifier.
rf_model = RandomForestClassifier(n_estimators=128, random_state=78)

# Fitting the model
rf_model = rf_model.fit(X_train_scaled, y_train)

# Evaluate the model
y_pred = rf_model.predict(X_test_scaled)
print(f" Random forest predictive accuracy: {accuracy_score(y_test,y_pred):.3f}")

 Random forest predictive accuracy: 0.918

In [8]:
# Define the model - deep neural net
number_input_features = len(X_train_scaled[0])
hidden_nodes_layer1 = 8
hidden_nodes_layer2 = 4

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu")
)

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))


# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Compile the Sequential model together and customize metrics
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

# Train the model
fit_model = nn.fit(X_train_scaled, y_train, epochs=50)

# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Epoch 1/50
1957/1957 [==============================] - 4s 2ms/step - loss: 0.3255 - accuracy: 0.8590
Epoch 2/50
1957/1957 [==============================] - 3s 1ms/step - loss: 0.2053 - accuracy: 0.9019
Epoch 3/50
1957/1957 [==============================] - 3s 2ms/step - loss: 0.1757 - accuracy: 0.9111
Epoch 4/50
1957/1957 [==============================] - 3s 1ms/step - loss: 0.1652 - accuracy: 0.9258
Epoch 5/50
1957/1957 [==============================] - 3s 1ms/step - loss: 0.1581 - accuracy: 0.9283
Epoch 6/50
1957/1957 [==============================] - 3s 1ms/step - loss: 0.1539 - accuracy: 0.9290
Epoch 7/50
1957/1957 [==============================] - 3s 1ms/step - loss: 0.1505 - accuracy: 0.9312
Epoch 8/50
1957/1957 [==============================] - 3s 1ms/step - loss: 0.1476 - accuracy: 0.9316
Epoch 9/50
1957/1957 [==============================] - 3s 1ms/step - loss: 0.1447 - accuracy: 0.9322
Epoch 10/50
1957/1957 [==============================] - 3s 1ms/step - loss: 0.1427 - accuracy: 0.9330
Epoch 11/50
1957/1957 [==============================] - 3s 1ms/step - loss: 0.1406 - accuracy: 0.9335
Epoch 12/50
1957/1957 [==============================] - 3s 1ms/step - loss: 0.1389 - accuracy: 0.9342
Epoch 13/50
1957/1957 [==============================] - 3s 1ms/step - loss: 0.1378 - accuracy: 0.9342
Epoch 14/50
1957/1957 [==============================] - 3s 2ms/step - loss: 0.1367 - accuracy: 0.9349
Epoch 15/50
1957/1957 [==============================] - 3s 2ms/step - loss: 0.1353 - accuracy: 0.9352
Epoch 16/50
1957/1957 [==============================] - 3s 2ms/step - loss: 0.1344 - accuracy: 0.9360
Epoch 17/50
1957/1957 [==============================] - 3s 1ms/step - loss: 0.1329 - accuracy: 0.9361
Epoch 18/50
1957/1957 [==============================] - 3s 1ms/step - loss: 0.1322 - accuracy: 0.9363
Epoch 19/50
1957/1957 [==============================] - 3s 1ms/step - loss: 0.1315 - accuracy: 0.9370
Epoch 20/50
1957/1957 [==============================] - 3s 1ms/step - loss: 0.1308 - accuracy: 0.9373
Epoch 21/50
1957/1957 [==============================] - 3s 1ms/step - loss: 0.1300 - accuracy: 0.9379
Epoch 22/50
1957/1957 [==============================] - 3s 1ms/step - loss: 0.1294 - accuracy: 0.9380
Epoch 23/50
1957/1957 [==============================] - 3s 1ms/step - loss: 0.1289 - accuracy: 0.9380
Epoch 24/50
1957/1957 [==============================] - 3s 1ms/step - loss: 0.1284 - accuracy: 0.9384
Epoch 25/50
1957/1957 [==============================] - 3s 1ms/step - loss: 0.1282 - accuracy: 0.9384
Epoch 26/50
1957/1957 [==============================] - 3s 2ms/step - loss: 0.1278 - accuracy: 0.9386
Epoch 27/50
1957/1957 [==============================] - 3s 2ms/step - loss: 0.1268 - accuracy: 0.9388
Epoch 28/50
1957/1957 [==============================] - 4s 2ms/step - loss: 0.1266 - accuracy: 0.9389
Epoch 29/50
1957/1957 [==============================] - 3s 2ms/step - loss: 0.1264 - accuracy: 0.9391
Epoch 30/50
1957/1957 [==============================] - 3s 2ms/step - loss: 0.1259 - accuracy: 0.9396
Epoch 31/50
1957/1957 [==============================] - 3s 2ms/step - loss: 0.1256 - accuracy: 0.9397
Epoch 32/50
1957/1957 [==============================] - 3s 2ms/step - loss: 0.1253 - accuracy: 0.9400
Epoch 33/50
1957/1957 [==============================] - 4s 2ms/step - loss: 0.1252 - accuracy: 0.9398
Epoch 34/50
1957/1957 [==============================] - 4s 2ms/step - loss: 0.1252 - accuracy: 0.9398
Epoch 35/50
1957/1957 [==============================] - 4s 2ms/step - loss: 0.1250 - accuracy: 0.9401
Epoch 36/50
1957/1957 [==============================] - 3s 1ms/step - loss: 0.1248 - accuracy: 0.9396
Epoch 37/50
1957/1957 [==============================] - 4s 2ms/step - loss: 0.1244 - accuracy: 0.9400
Epoch 38/50
1957/1957 [==============================] - 3s 2ms/step - loss: 0.1247 - accuracy: 0.9402
Epoch 39/50
1957/1957 [==============================] - 3s 2ms/step - loss: 0.1241 - accuracy: 0.9396
Epoch 40/50
1957/1957 [==============================] - 3s 2ms/step - loss: 0.1238 - accuracy: 0.9398
Epoch 41/50
1957/1957 [==============================] - 3s 2ms/step - loss: 0.1235 - accuracy: 0.9402
Epoch 42/50
1957/1957 [==============================] - 3s 2ms/step - loss: 0.1232 - accuracy: 0.9405
Epoch 43/50
1957/1957 [==============================] - 3s 2ms/step - loss: 0.1234 - accuracy: 0.9400
Epoch 44/50
1957/1957 [==============================] - 3s 2ms/step - loss: 0.1230 - accuracy: 0.9401
Epoch 45/50
1957/1957 [==============================] - 4s 2ms/step - loss: 0.1229 - accuracy: 0.9402
Epoch 46/50
1957/1957 [==============================] - 4s 2ms/step - loss: 0.1226 - accuracy: 0.9405
Epoch 47/50
1957/1957 [==============================] - 4s 2ms/step - loss: 0.1226 - accuracy: 0.9406
Epoch 48/50
1957/1957 [==============================] - 3s 2ms/step - loss: 0.1222 - accuracy: 0.9400
Epoch 49/50
1957/1957 [==============================] - 3s 2ms/step - loss: 0.1224 - accuracy: 0.9407
Epoch 50/50
1957/1957 [==============================] - 3s 2ms/step - loss: 0.1220 - accuracy: 0.9404
653/653 - 1s - loss: 0.2650 - accuracy: 0.9020 - 533ms/epoch - 816us/step
Loss: 0.2650066316127777, Accuracy: 0.901964545249939